apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccer-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccer-api
  template:
    metadata:
      labels:
        app: soccer-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: soccer-api
          image: ghcr.io/10peter/soccer-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

