apiVersion: v1
kind: Service
metadata:
  name: soccer-api-service
  namespace: soccer
  labels:
    app: soccer-api
spec:
  type: LoadBalancer
  selector:
    app: soccer-api
  ports:
    - name: http
      port: 80
      targetPort: 8000

